### ISSUE TITLE
Getting temperature and Irradiance

### ISSUE THREAD

**Issue by Cuervocartoon** [erijo/sunnyportal-py#11]
Hello and first at all let me thank you for your work, It has been very useful for me and my teamwork.

Additionally, for the power of plants, there are other two variables the Irradiance and the Temperature. We were looking at how to getting these with no luck.

Maybe do you have any ideas on how to construct the request for this information or maybe where we can search for it?

Thank you again.

**Comment by joebe975** [comment]
What temperature and irradiance are you referring to? Do you mean irradiance as in power per area? Temperature of the solar panels, the converter or outdoor? Where do you currently find these values?

**Comment by Cuervocartoon** [comment]
Thank's for your answer.

I'm talking about the module temperature (also it's possible to get the outdoor temperature) and the irradiance (exactly the power per area) in the place. These values are stored and reported on the webpage and the plant has a CLUSTER CONTROLLER withs the parameters.

**Comment by joebe975** [comment]
Do you get the irradiance per panel or the sum? If it's the sum, I suppose you can simply calculate it yourself based on the power measurements.

I don't have any cluster controller, so I suppose you have some additional hardware.

**Comment by Cuervocartoon** [comment]
Actually, the irradiance is used in order to calculate the efficiency of the panel as well as the temperature, so we need the measure regarding the needs. Thanks in advance.

**Comment by joebe975** [comment]
It didn't answer the question. I don't understand what exactly you have and get reported. Do you get a temperature measures for each solar panel? Does the irradiance refer to the actual irradiance with respect to atmosphere, clouds, shadows, diffraction, refraction, reflection, panel angles, etc, or do you mean a theoretical irradiance given the rough coordinates of your panels? That is, are those measured by hardware on site, or are they simply something they estimate based on some rough values? In the latter case, I suppose you can get these values independently of sunny portal. If it's based on special hardware on site, there is nothing I can do, since I don't see such measurements.

Did I understand you correctly that you have a tab in the sunny portal page called "cluster controller"? Was it there from start, or how did you get it?

**Comment by Cuervocartoon** [comment]
Indeed, I have additional hardware that measures these values, temperature, and irradiance, the hardware it's connected to the plant and I have a page with these values and takes the values from the controller.
I share the image from the webpage in the following link: https://drive.google.com/file/d/1N9FjQkoAeIW0_wNeApSJAyMdRumwfVaJ/view?usp=sharing

**Comment by erijo** [comment]
I think you need to experiment a bit with the existing methods and see if any of those returns something that looks like it could include the data you want.  In 6bfd33af I added support for getting devices for a solar plant and their parameters. Perhaps you can try and see if the hardware that measures the temperature and irradiance is reported as a special device. Enable the debug code in testclient.py to get the parameters and look at the XML in the debug log and see if you can find the device you're looking for.

**Comment by Cuervocartoon** [comment]
Ok, I'll do that. Many thanks for your answer.
